{% set name = "pyxdg" %}
{% set version = "0.27" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 80bd93aae5ed82435f20462ea0208fb198d8eec262e831ee06ce9ddb6b91c5a5

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - xdg

about:
  home: http://freedesktop.org/wiki/Software/pyxdg
  license: GNU Lesser General Public v2 (LGPLv2)
  license_family: LGPL
  license_file: COPYING
  summary: PyXDG contains implementations of freedesktop.org standards in python.
  description: PyXDG is a python library to access freedesktop.org standards

extra:
  recipe-maintainers:
    - marcelotrevisani
