travis:
  secure:
    BINSTAR_TOKEN: Vz4U9M8D2muNe780+GekiJJi5js+0NyNlQgse5zowXzS7ToNzr/UOCoysURWGv6xknq5wvme90ir7Qy7G2GTgVh08CAVI2SApzKcXHpg3+60LpIMNII4TqyCT67VQGPWsbqHz/9EEC0WVsMW37xSG8rSOIl8uZ4raG07ogmfVJS4pOfGmAa0yqpYU7ymE3n3sHfzBF8CTbRCWGZ2nVqPo8U281UB96ebCDYs7RQWBClzSqHK8C0BrynP1ZGr8+F7ODr+CFvDq5imLhlXsSHE00Js2RvspmOamcbm/Z1Yq06ad77ZBXIAfaiNdcBHUAZ5LL0C6GnFs4emhz/yEEbYSKpFw5PVrOAxPR8x7HcHUvvgNhRTidit/VMs/xI/IyIlwtXZ4+pOBg4pD1DXGQJZjmHEz/hmC9x3XgXdHvejItZ6GAyceoMtg6OZsHnRO1E2p1+qQ61BNtPNnvm6y70C7pDhVWaq7WwxOv5TfmAM65MEtnMxfvxsewFWW9WKYmFrUnxzY9CrSoDzoTTZbrWgR+JNMwIgcGBOFqvJVG1md+nCKNWbIRf+x4UIkYAwebCCAdNpyw8Bw7HiCRade+1M3ob8zRxLgi4cM2/gCyH0uimpbq28jLLOZVFKs86yNX0CnQHuonmVB//gFWZg2U1A2J5hRLIk3z+Lo2zQuy1YBr0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
